from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from transformers import AutoTokenizer

from .config import load_config, ensure_output_dir, save_resolved_config
from .utils import set_seed, get_device, save_json
from .data import (
    load_sequences_for_dataset,
    concat_dataset_splits,
    build_loader_from_sequences,
)
from .model import LogSLMNC
from .train import train_normality
from .losses import compute_center
from .scoring import (
    score_loader,
    evaluate_scores,
    save_classification_report_files,
)


# ======================================================
# COMMON HELPERS
# ======================================================

def make_model_and_tokenizer(cfg, device):
    model_cfg = cfg["model"]

    tokenizer = AutoTokenizer.from_pretrained(model_cfg["student_name"])

    model = LogSLMNC(
        backbone_name=model_cfg["student_name"],
        projection_dim=model_cfg["projection_dim"],
        dropout=model_cfg["dropout"],
        freeze_backbone=model_cfg.get("freeze_backbone", False),
    ).to(device)

    return model, tokenizer


def make_loader(cfg, seq_df, tokenizer, shuffle: bool, balanced: bool = False):
    return build_loader_from_sequences(
        seq_df=seq_df,
        tokenizer=tokenizer,
        max_length=cfg["model"]["max_length"],
        batch_size=cfg["training"]["batch_size"],
        mlm_probability=cfg["mlm"]["mlm_probability"],
        shuffle=shuffle,
        use_dataset_balanced_sampler=balanced,
    )


def get_center_config(cfg):
    center_cfg = cfg.get("normal_center", {})

    return {
        "num_prototypes": int(center_cfg.get("num_prototypes", 1)),
        "prototype_method": center_cfg.get("prototype_method", "kmeans"),
        "seed": int(cfg["experiment"].get("seed", 42)),
    }


def load_saved_model_tokenizer_center(
    cfg,
    out_dir: Path,
    device,
    center_filename: str,
):
    model_path = out_dir / "model.pt"
    center_path = out_dir / center_filename
    tokenizer_path = out_dir / "tokenizer"

    if not model_path.exists():
        raise FileNotFoundError(
            f"Saved model not found: {model_path}\n"
            "Run stage: train first."
        )

    if not center_path.exists():
        raise FileNotFoundError(
            f"Saved center/prototypes not found: {center_path}\n"
            "Run stage: train first."
        )

    if not tokenizer_path.exists():
        raise FileNotFoundError(
            f"Saved tokenizer not found: {tokenizer_path}\n"
            "Run stage: train first."
        )

    print(f"[Loading model] {model_path}")
    print(f"[Loading center/prototypes] {center_path}")
    print(f"[Loading tokenizer] {tokenizer_path}")

    tokenizer = AutoTokenizer.from_pretrained(tokenizer_path)

    model = LogSLMNC(
        backbone_name=cfg["model"]["student_name"],
        projection_dim=cfg["model"]["projection_dim"],
        dropout=cfg["model"]["dropout"],
        freeze_backbone=cfg["model"].get("freeze_backbone", False),
    ).to(device)

    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    center = torch.load(center_path, map_location="cpu")

    return model, tokenizer, center


# ======================================================
# ROBUST SCORE NORMALIZATION HELPERS
# ======================================================
#
# IMPORTANT DESIGN:
#   * NO real anomalous validation labels are used.
#   * NO test data/test scores/test labels are used for tuning.
#   * MLM loss and center distance are normalized using statistics fitted only
#     on NORMAL validation samples.
#   * The normal validation split is divided into FIT and TUNE subsets.
#   * Synthetic anomaly-like sequences are created only from TUNE normals.
#   * A small validation-only grid selects ONLY MLM/center weights.
#   * The threshold percentile is FIXED globally at 95.0.
#   * Selected parameters are frozen before the TEST split is loaded.
# ======================================================

ROBUST_SCORING_VERSION = "ROBUST_NORMALIZED_SCORE_V3_WEIGHT_ONLY_TUNING"

# ------------------------------------------------------------------
# Validation-only tuning configuration.
# ------------------------------------------------------------------
# IMPORTANT:
#   * These candidates are searched ONLY inside the NORMAL validation split.
#   * Synthetic anomaly labels are generated by this file; no real anomalous
#     validation labels are used.
#   * Test data/test scores/test labels are not loaded until tuning is frozen.
#   * Keep these candidate grids identical across datasets for fair reporting.
# ------------------------------------------------------------------
ROBUST_POSITIVE_ONLY = True
ROBUST_EPSILON = 1e-12

TUNING_FIT_RATIO = 0.60

# Tune ONLY the score weights. The threshold percentile is fixed globally.
TUNING_WEIGHT_CANDIDATES = [
    (0.00, 1.00),
    (0.10, 0.90),
    (0.20, 0.80),
    (0.30, 0.70),
    (0.40, 0.60),
    (0.50, 0.50),  # baseline
    (0.60, 0.40),
    (0.70, 0.30),
    (0.80, 0.20),
    (0.90, 0.10),
    (1.00, 0.00),
]
FIXED_THRESHOLD_PERCENTILE = 95.0
BASELINE_MLM_WEIGHT = 0.50
BASELINE_CENTER_WEIGHT = 0.50
MIN_SYNTHETIC_F1_GAIN = 0.01
TUNING_SYNTHETIC_PER_NORMAL = 1

# Temporary weights used only while score_loader extracts mlm_loss and
# center_distance. The temporary score column is overwritten later.
COMPONENT_EXTRACTION_MLM_WEIGHT = 0.5
COMPONENT_EXTRACTION_CENTER_WEIGHT = 0.5


def _fit_robust_location_scale(values, epsilon: float):
    """
    Fit a robust location and scale using NORMAL validation values only.

    Main scale       : 1.4826 * MAD
    Fallback 1       : IQR / 1.349
    Fallback 2       : standard deviation
    Final fallback   : 1.0

    The fallbacks only prevent division by zero for nearly constant features.
    """
    x = np.asarray(values, dtype=np.float64)
    x = x[np.isfinite(x)]

    if x.size == 0:
        raise ValueError("Cannot fit robust normalization on an empty score array.")

    median = float(np.median(x))
    raw_mad = float(np.median(np.abs(x - median)))
    scaled_mad = float(1.4826 * raw_mad)

    q25, q75 = np.quantile(x, [0.25, 0.75])
    iqr = float(q75 - q25)
    iqr_scale = float(iqr / 1.349) if iqr > 0.0 else 0.0
    std = float(np.std(x))

    if scaled_mad > epsilon:
        scale = scaled_mad
        scale_source = "scaled_mad"
    elif iqr_scale > epsilon:
        scale = iqr_scale
        scale_source = "iqr"
    elif std > epsilon:
        scale = std
        scale_source = "std"
    else:
        scale = 1.0
        scale_source = "constant_fallback"

    return {
        "median": median,
        "raw_mad": raw_mad,
        "scale": float(scale),
        "scale_source": scale_source,
        "q25": float(q25),
        "q75": float(q75),
        "min": float(np.min(x)),
        "max": float(np.max(x)),
        "n": int(x.size),
    }


def fit_robust_score_normalizer(val_normal_scores: pd.DataFrame) -> dict:
    """
    STEP 3 of prediction:
    Fit robust normalization parameters using NORMAL VALIDATION ONLY.

    Validation labels are not used for optimization. The optional label check
    below is only a safety assertion that the dataframe really contains normal
    samples exclusively.
    """
    required = {"mlm_loss", "center_distance"}
    missing = required - set(val_normal_scores.columns)
    if missing:
        raise ValueError(
            f"Robust normalization is missing required columns: {sorted(missing)}"
        )

    if "label" in val_normal_scores.columns:
        labels = set(
            val_normal_scores["label"]
            .dropna()
            .astype(int)
            .unique()
            .tolist()
        )
        if labels - {0}:
            raise ValueError(
                "Robust normalization received anomalous validation samples. "
                "Calibration must use NORMAL validation samples only."
            )

    eps = ROBUST_EPSILON

    params = {
        "method": "normal_validation_robust_component_normalization",
        "version": ROBUST_SCORING_VERSION,
        "mlm_weight": COMPONENT_EXTRACTION_MLM_WEIGHT,
        "center_weight": COMPONENT_EXTRACTION_CENTER_WEIGHT,
        "positive_only": ROBUST_POSITIVE_ONLY,
        "epsilon": eps,
        "mlm_loss": _fit_robust_location_scale(
            val_normal_scores["mlm_loss"].to_numpy(),
            eps,
        ),
        "center_distance": _fit_robust_location_scale(
            val_normal_scores["center_distance"].to_numpy(),
            eps,
        ),
    }

    print("=" * 80)
    print("[ROBUST SCORE NORMALIZATION - FIT ON NORMAL VALIDATION ONLY]")
    print(f"[Version] {ROBUST_SCORING_VERSION}")
    print(f"normal validation samples : {len(val_normal_scores)}")
    print(f"MLM weight                : {params['mlm_weight']:.6f}")
    print(f"Center weight             : {params['center_weight']:.6f}")
    print(f"Positive deviations only  : {params['positive_only']}")
    print(
        "MLM median / scale       : "
        f"{params['mlm_loss']['median']:.8f} / "
        f"{params['mlm_loss']['scale']:.8f} "
        f"({params['mlm_loss']['scale_source']})"
    )
    print(
        "Center median / scale    : "
        f"{params['center_distance']['median']:.8f} / "
        f"{params['center_distance']['scale']:.8f} "
        f"({params['center_distance']['scale_source']})"
    )
    print("=" * 80)

    return params


def apply_robust_score_normalization(
    score_df: pd.DataFrame,
    robust_params: dict,
) -> pd.DataFrame:
    """
    Apply FROZEN robust-normalization parameters to validation or test scores.

    No fitting or parameter search happens here.
    """
    required = {"mlm_loss", "center_distance"}
    missing = required - set(score_df.columns)
    if missing:
        raise ValueError(
            f"Cannot apply robust scoring; missing columns: {sorted(missing)}"
        )

    out = score_df.copy()

    mlm_median = float(robust_params["mlm_loss"]["median"])
    mlm_scale = float(robust_params["mlm_loss"]["scale"])
    center_median = float(robust_params["center_distance"]["median"])
    center_scale = float(robust_params["center_distance"]["scale"])

    z_mlm = (out["mlm_loss"].to_numpy(dtype=np.float64) - mlm_median) / mlm_scale
    z_center = (
        out["center_distance"].to_numpy(dtype=np.float64) - center_median
    ) / center_scale

    out["robust_z_mlm"] = z_mlm
    out["robust_z_center"] = z_center

    # Anomaly evidence is one-sided: only deviations ABOVE normal median add
    # anomaly evidence. A very low value in one component therefore cannot
    # cancel a strong anomalous deviation in the other component.
    if bool(robust_params.get("positive_only", True)):
        mlm_component = np.maximum(z_mlm, 0.0)
        center_component = np.maximum(z_center, 0.0)
    else:
        mlm_component = z_mlm
        center_component = z_center

    out["robust_mlm_component"] = mlm_component
    out["robust_center_component"] = center_component

    out["score"] = (
        float(robust_params["mlm_weight"]) * mlm_component
        + float(robust_params["center_weight"]) * center_component
    )

    return out



def split_normal_validation_for_tuning(
    val_normal_df: pd.DataFrame,
    seed: int,
    fit_ratio: float = TUNING_FIT_RATIO,
):
    """
    Split NORMAL validation sequences into two disjoint subsets:

      fit subset  -> robust median/MAD + candidate threshold estimation
      tune subset -> real normal examples used against synthetic anomalies
                     to choose weights and percentile

    No anomalous validation samples are used.
    """
    if len(val_normal_df) < 4:
        raise ValueError(
            "Validation-only tuning needs at least 4 normal validation sequences."
        )

    if "label" in val_normal_df.columns:
        labels = set(val_normal_df["label"].dropna().astype(int).unique().tolist())
        if labels - {0}:
            raise ValueError(
                "Validation tuning received real anomalous validation samples. "
                "Only NORMAL validation samples are allowed."
            )

    fit_ratio = float(fit_ratio)
    if not 0.0 < fit_ratio < 1.0:
        raise ValueError("TUNING_FIT_RATIO must be between 0 and 1.")

    rng = np.random.default_rng(int(seed))
    indices = val_normal_df.index.to_numpy().copy()
    rng.shuffle(indices)

    n_fit = int(round(fit_ratio * len(indices)))
    n_fit = min(max(n_fit, 2), len(indices) - 2)

    fit_df = val_normal_df.loc[indices[:n_fit]].reset_index(drop=True)
    tune_df = val_normal_df.loc[indices[n_fit:]].reset_index(drop=True)

    print("=" * 80)
    print("[NORMAL VALIDATION SPLIT FOR TUNING]")
    print(f"total normal validation : {len(val_normal_df)}")
    print(f"fit subset              : {len(fit_df)}")
    print(f"tune subset             : {len(tune_df)}")
    print("Real anomaly validation labels used: NO")
    print("=" * 80)

    return fit_df, tune_df


def _split_sequence_events(sequence: str, event_separator: str):
    events = [e.strip() for e in str(sequence).split(event_separator)]
    return [e for e in events if e]


def make_synthetic_anomaly_sequences(
    normal_tune_df: pd.DataFrame,
    cfg,
    seed: int,
    synthetic_per_normal: int = TUNING_SYNTHETIC_PER_NORMAL,
):
    """
    Create synthetic anomaly-like validation sequences ONLY from NORMAL
    validation sequences.

    Corruptions are deliberately simple and model-agnostic:
      1) swap two events
      2) delete one event
      3) duplicate one event
      4) replace one event with an event from another normal sequence

    The generated label=1 is a SYNTHETIC label created by this procedure.
    It is not read from the dataset's real anomaly labels.
    """
    if len(normal_tune_df) == 0:
        raise ValueError("Cannot create synthetic anomalies from an empty tune set.")

    rng = np.random.default_rng(int(seed))
    event_separator = cfg.get("text", {}).get("event_separator", " [SEP] ")

    parsed = [
        _split_sequence_events(seq, event_separator)
        for seq in normal_tune_df["sequence"].astype(str).tolist()
    ]
    donor_pool = [event for events in parsed for event in events]

    if not donor_pool:
        raise ValueError("No events are available for synthetic anomaly generation.")

    rows = []
    operations = ["swap", "delete", "duplicate", "replace"]
    synthetic_per_normal = max(1, int(synthetic_per_normal))

    for row_idx, row in normal_tune_df.reset_index(drop=True).iterrows():
        original_events = list(parsed[row_idx])
        if not original_events:
            continue

        for copy_idx in range(synthetic_per_normal):
            events = list(original_events)
            op = operations[(row_idx * synthetic_per_normal + copy_idx) % len(operations)]

            if op == "swap" and len(events) >= 2:
                i, j = rng.choice(len(events), size=2, replace=False)
                events[int(i)], events[int(j)] = events[int(j)], events[int(i)]

            elif op == "delete" and len(events) >= 2:
                del events[int(rng.integers(0, len(events)))]

            elif op == "duplicate":
                i = int(rng.integers(0, len(events)))
                events.insert(i + 1, events[i])

            else:  # replace, or fallback when swap/delete is impossible
                i = int(rng.integers(0, len(events)))
                replacement = str(donor_pool[int(rng.integers(0, len(donor_pool)))])
                if replacement == events[i] and len(donor_pool) > 1:
                    # Try once more to avoid a no-op replacement.
                    replacement = str(donor_pool[int(rng.integers(0, len(donor_pool)))])
                events[i] = replacement

            synthetic_sequence = event_separator.join(events)

            # Safety fallback: guarantee the synthetic sequence differs from
            # the original normal sequence.
            if synthetic_sequence == str(row["sequence"]):
                events = list(original_events)
                i = int(rng.integers(0, len(events)))
                events.insert(i + 1, events[i])
                synthetic_sequence = event_separator.join(events)

            synthetic_row = row.copy()
            synthetic_row["sequence"] = synthetic_sequence
            synthetic_row["label"] = 1  # synthetic label, not a real dataset label
            synthetic_row["group_id"] = (
                f"synthetic::{row.get('group_id', row_idx)}::{copy_idx}"
            )
            synthetic_row["num_events"] = len(events)
            rows.append(synthetic_row.to_dict())

    synthetic_df = pd.DataFrame(rows)
    if synthetic_df.empty:
        raise ValueError("Synthetic anomaly generation produced no sequences.")

    print("=" * 80)
    print("[SYNTHETIC VALIDATION ANOMALIES]")
    print(f"real normal tune sequences : {len(normal_tune_df)}")
    print(f"synthetic anomalies        : {len(synthetic_df)}")
    print("Real anomalous validation samples used: NO")
    print("=" * 80)

    return synthetic_df.reset_index(drop=True)


def _combine_robust_components(score_df: pd.DataFrame, mlm_weight: float, center_weight: float):
    return (
        float(mlm_weight) * score_df["robust_mlm_component"].to_numpy(dtype=np.float64)
        + float(center_weight) * score_df["robust_center_component"].to_numpy(dtype=np.float64)
    )


def tune_weights_on_synthetic_validation(
    fit_scores: pd.DataFrame,
    tune_normal_scores: pd.DataFrame,
    tune_synthetic_scores: pd.DataFrame,
):
    """
    Tune ONLY MLM/center weights using validation-derived data.

    IMPORTANT:
      * Threshold percentile is fixed globally at 95.0.
      * No real anomalous validation labels are used.
      * No test data/test scores/test labels are used.
      * The 0.5/0.5 weight pair is the baseline.
      * A tuned candidate is accepted only if, on the synthetic-validation
        task, precision, recall, anomaly F1 and macro F1 are not lower than
        the baseline and anomaly F1 improves by at least 0.01.
      * Otherwise, the baseline 0.5/0.5 weights are retained.

    Candidate thresholds are always estimated from the disjoint normal FIT
    subset at FIXED_THRESHOLD_PERCENTILE.
    """
    records = []

    y_true = np.concatenate(
        [
            np.zeros(len(tune_normal_scores), dtype=np.int64),
            np.ones(len(tune_synthetic_scores), dtype=np.int64),
        ]
    )

    for mlm_weight, center_weight in TUNING_WEIGHT_CANDIDATES:
        fit_combined = _combine_robust_components(
            fit_scores, mlm_weight, center_weight
        )
        tune_normal_combined = _combine_robust_components(
            tune_normal_scores, mlm_weight, center_weight
        )
        tune_synthetic_combined = _combine_robust_components(
            tune_synthetic_scores, mlm_weight, center_weight
        )
        tune_combined = np.concatenate(
            [tune_normal_combined, tune_synthetic_combined]
        )

        threshold = float(
            np.percentile(fit_combined, FIXED_THRESHOLD_PERCENTILE)
        )
        y_pred = (tune_combined > threshold).astype(np.int64)

        macro_f1 = float(
            f1_score(y_true, y_pred, average="macro", zero_division=0)
        )
        anomaly_f1 = float(
            f1_score(y_true, y_pred, average="binary", zero_division=0)
        )
        anomaly_precision = float(
            precision_score(y_true, y_pred, zero_division=0)
        )
        anomaly_recall = float(
            recall_score(y_true, y_pred, zero_division=0)
        )
        accuracy = float(accuracy_score(y_true, y_pred))

        records.append(
            {
                "mlm_weight": float(mlm_weight),
                "center_weight": float(center_weight),
                "percentile": float(FIXED_THRESHOLD_PERCENTILE),
                "fit_threshold": threshold,
                "macro_f1": macro_f1,
                "anomaly_f1": anomaly_f1,
                "anomaly_precision": anomaly_precision,
                "anomaly_recall": anomaly_recall,
                "accuracy": accuracy,
            }
        )

    tuning_df = pd.DataFrame(records)

    baseline_mask = (
        np.isclose(tuning_df["mlm_weight"], BASELINE_MLM_WEIGHT)
        & np.isclose(tuning_df["center_weight"], BASELINE_CENTER_WEIGHT)
    )
    if not baseline_mask.any():
        raise ValueError(
            "Baseline 0.5/0.5 weights are missing from TUNING_WEIGHT_CANDIDATES."
        )

    baseline = tuning_df.loc[baseline_mask].iloc[0].to_dict()

    # Conservative multi-metric gate: do not accept a candidate that buys one
    # metric by sacrificing another on the validation-only synthetic task.
    eligible = tuning_df[
        (tuning_df["anomaly_precision"] >= baseline["anomaly_precision"])
        & (tuning_df["anomaly_recall"] >= baseline["anomaly_recall"])
        & (tuning_df["anomaly_f1"] >= baseline["anomaly_f1"] + MIN_SYNTHETIC_F1_GAIN)
        & (tuning_df["macro_f1"] >= baseline["macro_f1"])
    ].copy()

    if eligible.empty:
        best = baseline
        selection_reason = (
            "fallback_to_baseline_no_candidate_improved_precision_recall_"
            "and_f1_together"
        )
    else:
        eligible["min_precision_recall"] = np.minimum(
            eligible["anomaly_precision"], eligible["anomaly_recall"]
        )
        eligible = eligible.sort_values(
            ["anomaly_f1", "min_precision_recall", "macro_f1", "accuracy"],
            ascending=[False, False, False, False],
        )
        best = eligible.iloc[0].to_dict()
        selection_reason = "accepted_validation_candidate"

    tuning_df["is_baseline"] = baseline_mask
    tuning_df["is_selected"] = (
        np.isclose(tuning_df["mlm_weight"], float(best["mlm_weight"]))
        & np.isclose(tuning_df["center_weight"], float(best["center_weight"]))
    )
    tuning_df = tuning_df.sort_values(
        ["is_selected", "anomaly_f1", "macro_f1"],
        ascending=[False, False, False],
    ).reset_index(drop=True)

    best["selection_reason"] = selection_reason
    best["baseline_anomaly_precision"] = float(baseline["anomaly_precision"])
    best["baseline_anomaly_recall"] = float(baseline["anomaly_recall"])
    best["baseline_anomaly_f1"] = float(baseline["anomaly_f1"])
    best["baseline_macro_f1"] = float(baseline["macro_f1"])

    print("=" * 80)
    print("[VALIDATION-ONLY WEIGHT TUNING - FIXED 95TH PERCENTILE]")
    print("Selection uses: real NORMAL validation + SYNTHETIC anomalies")
    print("Real anomalous validation labels used: NO")
    print("Test data/test scores/test labels used: NO")
    print(f"fixed percentile          : {FIXED_THRESHOLD_PERCENTILE:.2f}")
    print(
        f"baseline weights          : MLM={BASELINE_MLM_WEIGHT:.2f}, "
        f"Center={BASELINE_CENTER_WEIGHT:.2f}"
    )
    print(f"baseline precision        : {baseline['anomaly_precision']:.4f}")
    print(f"baseline recall           : {baseline['anomaly_recall']:.4f}")
    print(f"baseline anomaly F1       : {baseline['anomaly_f1']:.4f}")
    print(f"selected MLM weight       : {best['mlm_weight']:.2f}")
    print(f"selected center weight    : {best['center_weight']:.2f}")
    print(f"selected precision        : {best['anomaly_precision']:.4f}")
    print(f"selected recall           : {best['anomaly_recall']:.4f}")
    print(f"selected anomaly F1       : {best['anomaly_f1']:.4f}")
    print(f"selected macro F1         : {best['macro_f1']:.4f}")
    print(f"selection reason          : {selection_reason}")
    print("=" * 80)

    return best, tuning_df


def fit_and_tune_robust_scoring(
    cfg,
    val_normal_df: pd.DataFrame,
    model,
    tokenizer,
    center,
    device,
    seed: int,
    desc_prefix: str,
):
    """
    Complete validation-only tuning pipeline.

    Returns final robust parameters + final threshold, both frozen BEFORE test.
    """
    fit_df, tune_normal_df = split_normal_validation_for_tuning(
        val_normal_df,
        seed=seed,
        fit_ratio=TUNING_FIT_RATIO,
    )
    tune_synthetic_df = make_synthetic_anomaly_sequences(
        tune_normal_df,
        cfg=cfg,
        seed=seed + 101,
        synthetic_per_normal=TUNING_SYNTHETIC_PER_NORMAL,
    )

    fit_loader = make_loader(cfg, fit_df, tokenizer, shuffle=False)
    tune_normal_loader = make_loader(cfg, tune_normal_df, tokenizer, shuffle=False)
    tune_synthetic_loader = make_loader(
        cfg, tune_synthetic_df, tokenizer, shuffle=False
    )

    fit_raw = score_loader(
        model,
        fit_loader,
        center,
        device,
        alpha_mlm=COMPONENT_EXTRACTION_MLM_WEIGHT,
        beta_center=COMPONENT_EXTRACTION_CENTER_WEIGHT,
        desc=f"{desc_prefix}: scoring normal FIT components",
    )
    tune_normal_raw = score_loader(
        model,
        tune_normal_loader,
        center,
        device,
        alpha_mlm=COMPONENT_EXTRACTION_MLM_WEIGHT,
        beta_center=COMPONENT_EXTRACTION_CENTER_WEIGHT,
        desc=f"{desc_prefix}: scoring normal TUNE components",
    )
    tune_synthetic_raw = score_loader(
        model,
        tune_synthetic_loader,
        center,
        device,
        alpha_mlm=COMPONENT_EXTRACTION_MLM_WEIGHT,
        beta_center=COMPONENT_EXTRACTION_CENTER_WEIGHT,
        desc=f"{desc_prefix}: scoring SYNTHETIC anomaly components",
    )

    # Fit normalization ONLY on the disjoint normal FIT subset.
    search_params = fit_robust_score_normalizer(fit_raw)
    fit_robust = apply_robust_score_normalization(fit_raw, search_params)
    tune_normal_robust = apply_robust_score_normalization(
        tune_normal_raw, search_params
    )
    tune_synthetic_robust = apply_robust_score_normalization(
        tune_synthetic_raw, search_params
    )

    best, tuning_df = tune_weights_on_synthetic_validation(
        fit_robust,
        tune_normal_robust,
        tune_synthetic_robust,
    )

    # --------------------------------------------------------------
    # Refit final normalizer on ALL normal validation samples AFTER
    # hyperparameters are selected. This uses no anomaly labels.
    # --------------------------------------------------------------
    all_normal_raw = pd.concat(
        [fit_raw, tune_normal_raw], axis=0, ignore_index=True
    )
    final_params = fit_robust_score_normalizer(all_normal_raw)
    final_params["mlm_weight"] = float(best["mlm_weight"])
    final_params["center_weight"] = float(best["center_weight"])
    final_params["selected_percentile"] = float(FIXED_THRESHOLD_PERCENTILE)
    final_params["tuning_fit_ratio"] = float(TUNING_FIT_RATIO)
    final_params["tuning_method"] = "normal_validation_plus_synthetic_anomalies"
    final_params["real_anomaly_validation_labels_used"] = False
    final_params["test_used_for_tuning"] = False
    final_params["synthetic_validation_metrics"] = {
        "precision": float(best["anomaly_precision"]),
        "recall": float(best["anomaly_recall"]),
        "anomaly_f1": float(best["anomaly_f1"]),
        "macro_f1": float(best["macro_f1"]),
        "accuracy": float(best["accuracy"]),
    }

    all_normal_robust = apply_robust_score_normalization(
        all_normal_raw, final_params
    )
    final_threshold = float(
        np.percentile(
            all_normal_robust["score"].to_numpy(dtype=np.float64),
            float(FIXED_THRESHOLD_PERCENTILE),
        )
    )
    final_params["threshold"] = final_threshold

    print("=" * 80)
    print("[FINAL FROZEN VALIDATION-SELECTED SCORING]")
    print(f"MLM weight    : {final_params['mlm_weight']:.2f}")
    print(f"Center weight : {final_params['center_weight']:.2f}")
    print(f"Percentile    : {FIXED_THRESHOLD_PERCENTILE:.2f} (fixed globally)")
    print(f"Threshold     : {final_threshold:.10f}")
    print("TEST HAS NOT BEEN LOADED YET")
    print("=" * 80)

    return final_params, final_threshold, all_normal_robust, tuning_df


def train_in_domain(cfg, config_path: str):
    """
    In-domain training stage only.

    Trains on normal sequences from one dataset and saves:
        model.pt
        normal_center.pt
        tokenizer/
        train_results.json

    It does NOT predict.
    """

    out_dir = ensure_output_dir(cfg)

    if cfg.get("outputs", {}).get("save_config", True):
        save_resolved_config(config_path, out_dir)

    set_seed(cfg["experiment"].get("seed", 42))
    device = get_device(cfg["training"].get("device", "auto"))

    mode_cfg = cfg["datasets"]["in_domain"]
    dataset_name = mode_cfg["dataset_name"]

    print("=" * 80)
    print("[Stage] TRAIN ONLY")
    print("[Mode] in_domain")
    print(f"[Dataset] {dataset_name}")
    print("=" * 80)

    train_df = load_sequences_for_dataset(
        cfg,
        dataset=dataset_name,
        split=mode_cfg["train_split"],
        normal_only=True,
    )

    val_df = load_sequences_for_dataset(
        cfg,
        dataset=dataset_name,
        split=mode_cfg["val_split"],
        normal_only=True,
    )

    print(
        f"[Sequences] train={len(train_df)} "
        f"val={len(val_df)}"
    )

    model, tokenizer = make_model_and_tokenizer(cfg, device)

    train_loader = make_loader(
        cfg,
        train_df,
        tokenizer,
        shuffle=True,
        balanced=cfg["training"].get("use_dataset_balanced_sampler", False),
    )

    val_loader = make_loader(
        cfg,
        val_df,
        tokenizer,
        shuffle=False,
    )

    history = train_normality(
        model=model,
        loader=train_loader,
        device=device,
        epochs=cfg["training"]["in_domain_epochs"],
        learning_rate=cfg["training"]["in_domain_lr"],
        weight_decay=cfg["training"]["weight_decay"],
        center_loss_weight=cfg["training"]["center_loss_weight"],
        gradient_clip_norm=cfg["training"].get("gradient_clip_norm"),
        stage_name="in-domain",
    )

    center_cfg = get_center_config(cfg)

    center = compute_center(
        model,
        val_loader,
        device,
        desc="Computing in-domain normal center/prototypes",
        num_prototypes=center_cfg["num_prototypes"],
        prototype_method=center_cfg["prototype_method"],
        seed=center_cfg["seed"],
    )

    print("[Saving trained model]")
    torch.save(model.state_dict(), out_dir / "model.pt")

    print("[Saving normal center/prototypes]")
    torch.save(center.cpu(), out_dir / "normal_center.pt")

    print("[Saving tokenizer]")
    tokenizer.save_pretrained(out_dir / "tokenizer")

    save_json(
        {
            "stage": "train",
            "mode": "in_domain",
            "dataset": dataset_name,
            "history": history,
            "normal_center": center_cfg,
            "saved_model": str(out_dir / "model.pt"),
            "saved_center": str(out_dir / "normal_center.pt"),
            "saved_tokenizer": str(out_dir / "tokenizer"),
        },
        out_dir / "train_results.json",
    )

    print("=" * 80)
    print("[IN-DOMAIN TRAINING FINISHED]")
    print(f"Saved model     : {out_dir / 'model.pt'}")
    print(f"Saved center    : {out_dir / 'normal_center.pt'}")
    print(f"Saved tokenizer : {out_dir / 'tokenizer'}")
    print("=" * 80)


# ======================================================
# MODE 1: IN-DOMAIN PREDICT ONLY
# ======================================================


def predict_in_domain(cfg):
    """
    In-domain prediction with validation-only tuning.

    DATA USAGE:
      1) Load trained model + normal center/prototypes.
      2) Load NORMAL validation only.
      3) Split normal validation into FIT and TUNE subsets.
      4) Generate synthetic anomalies from TUNE normal sequences only.
      5) Fit robust median/MAD normalization on FIT normals only.
      6) Tune ONLY MLM/center weights on:
             real TUNE normals vs synthetic TUNE anomalies.
         No real anomalous validation labels are used.
      7) Refit robust normalizer on all normal validation samples and freeze
         selected weights + fixed-percentile threshold.
      8) ONLY NOW load the held-out TEST set.
      9) Apply frozen scoring to TEST.
     10) Use TEST labels only for final evaluation.
    """
    out_dir = ensure_output_dir(cfg)

    seed = int(cfg["experiment"].get("seed", 42))
    set_seed(seed)
    device = get_device(cfg["training"].get("device", "auto"))

    mode_cfg = cfg["datasets"]["in_domain"]
    dataset_name = mode_cfg["dataset_name"]

    print("=" * 80)
    print("[Stage] PREDICT ONLY")
    print("[Mode] in_domain")
    print(f"[Dataset] {dataset_name}")
    print(f"[Scoring version] {ROBUST_SCORING_VERSION}")
    print("=" * 80)

    # STEP 1 - model/center
    print("[STEP 1/10] Load trained model, tokenizer, and normal center/prototypes")
    model, tokenizer, center = load_saved_model_tokenizer_center(
        cfg=cfg,
        out_dir=out_dir,
        device=device,
        center_filename="normal_center.pt",
    )

    # STEP 2 - normal validation only
    print("[STEP 2/10] Load NORMAL validation samples only")
    val_normal_df = load_sequences_for_dataset(
        cfg,
        dataset=dataset_name,
        split=mode_cfg["val_split"],
        normal_only=True,
    )
    print(f"[Normal validation sequences] {len(val_normal_df)}")

    # STEPS 3-7 - validation-only tuning and freezing
    print("[STEP 3-7/10] Validation-only WEIGHT tuning; percentile fixed at 95")
    robust_params, robust_threshold, robust_val_normal_scores, tuning_df = (
        fit_and_tune_robust_scoring(
            cfg=cfg,
            val_normal_df=val_normal_df,
            model=model,
            tokenizer=tokenizer,
            center=center,
            device=device,
            seed=seed,
            desc_prefix=f"{dataset_name} validation tuning",
        )
    )

    save_json(robust_params, out_dir / "robust_scoring_params.json")
    tuning_df.to_csv(out_dir / "robust_tuning_search.csv", index=False)
    robust_val_normal_scores.to_csv(
        out_dir / "robust_normal_validation_scores.csv", index=False
    )

    print("[TEST HAS NOT BEEN LOADED YET]")

    # STEP 8 - only now load test
    print("[STEP 8/10] Load held-out TEST only after tuning is frozen")
    test_df = load_sequences_for_dataset(
        cfg,
        dataset=dataset_name,
        split=mode_cfg["test_split"],
        normal_only=mode_cfg.get("test_normal_only", False),
    )
    print(f"[Test sequences] {len(test_df)}")

    test_loader = make_loader(cfg, test_df, tokenizer, shuffle=False)

    # STEP 9 - score/apply frozen params
    print("[STEP 9/10] Score TEST and apply FROZEN robust parameters")
    test_raw_scores = score_loader(
        model,
        test_loader,
        center,
        device,
        alpha_mlm=COMPONENT_EXTRACTION_MLM_WEIGHT,
        beta_center=COMPONENT_EXTRACTION_CENTER_WEIGHT,
        desc="Scoring held-out TEST components",
    )
    robust_test_scores = apply_robust_score_normalization(
        test_raw_scores, robust_params
    )
    robust_test_scores["prediction"] = (
        robust_test_scores["score"] > robust_threshold
    ).astype(int)

    # STEP 10 - final evaluation only
    print("[STEP 10/10] Use TEST labels only for final metrics")
    metrics = evaluate_scores(
        robust_test_scores,
        robust_threshold,
        normal_label=0,
    )

    save_classification_report_files(metrics, out_dir, prefix="test")
    robust_test_scores.to_csv(
        out_dir / cfg["outputs"].get("predictions_file", "predictions.csv"),
        index=False,
    )

    save_json(
        {
            "stage": "predict",
            "mode": "in_domain",
            "dataset": dataset_name,
            "metrics": metrics,
            "robust_scoring": robust_params,
            "robust_threshold": float(robust_threshold),
        },
        out_dir / cfg["outputs"].get("results_file", "results.json"),
    )

    print("=" * 80)
    print("[IN-DOMAIN PREDICTION FINISHED]")
    print("[Weight-Tuned Robust FINAL TEST Classification Report]")
    print(metrics["classification_report_text"])
    print("=" * 80)

def run_in_domain(cfg, config_path: str):
    """
    Full in-domain pipeline:
        train
        predict
    """

    train_in_domain(cfg, config_path)
    predict_in_domain(cfg)


# ======================================================
# MODE 2: FEW-SHOT TARGET ADAPTATION TRAIN ONLY
# ======================================================

def train_fewshot_target_adaptation(cfg, config_path: str):
    """
    Few-shot target adaptation training stage only.

    Trains:
        source normal model on source_datasets
        target adaptation on target normal subset

    Saves:
        model.pt
        target_normal_center.pt
        tokenizer/
        train_results.json

    It does NOT predict.
    """

    out_dir = ensure_output_dir(cfg)

    if cfg.get("outputs", {}).get("save_config", True):
        save_resolved_config(config_path, out_dir)

    set_seed(cfg["experiment"].get("seed", 42))
    device = get_device(cfg["training"].get("device", "auto"))

    mode_cfg = cfg["datasets"]["fewshot_target_adaptation"]
    source_datasets = mode_cfg["source_datasets"]
    target_dataset = mode_cfg["target_dataset"]

    print("=" * 80)
    print("[Stage] TRAIN ONLY")
    print("[Mode] fewshot_target_adaptation")
    print(f"[Source datasets] {source_datasets}")
    print(f"[Target dataset] {target_dataset}")
    print("=" * 80)

    source_train_df = concat_dataset_splits(
        cfg,
        datasets=source_datasets,
        split=mode_cfg["source_train_split"],
        normal_only=True,
    )

    target_adapt_df = load_sequences_for_dataset(
        cfg,
        dataset=target_dataset,
        split=mode_cfg["target_adapt_split"],
        normal_only=True,
        target_normal_ratio=mode_cfg.get("target_normal_ratio"),
        target_normal_max_samples=mode_cfg.get("target_normal_max_samples"),
    )

    target_val_df = load_sequences_for_dataset(
        cfg,
        dataset=target_dataset,
        split=mode_cfg["target_val_split"],
        normal_only=True,
    )

    print(
        f"[Sequences] source_train={len(source_train_df)} "
        f"target_adapt={len(target_adapt_df)} "
        f"target_val={len(target_val_df)}"
    )

    model, tokenizer = make_model_and_tokenizer(cfg, device)

    source_loader = make_loader(
        cfg,
        source_train_df,
        tokenizer,
        shuffle=True,
        balanced=cfg["training"].get("balance_source_datasets", True),
    )

    target_adapt_loader = make_loader(
        cfg,
        target_adapt_df,
        tokenizer,
        shuffle=True,
    )

    target_val_loader = make_loader(
        cfg,
        target_val_df,
        tokenizer,
        shuffle=False,
    )

    source_history = train_normality(
        model=model,
        loader=source_loader,
        device=device,
        epochs=cfg["training"]["source_epochs"],
        learning_rate=cfg["training"]["source_lr"],
        weight_decay=cfg["training"]["weight_decay"],
        center_loss_weight=cfg["training"]["center_loss_weight"],
        gradient_clip_norm=cfg["training"].get("gradient_clip_norm"),
        stage_name="source",
    )

    target_history = train_normality(
        model=model,
        loader=target_adapt_loader,
        device=device,
        epochs=cfg["training"]["target_adapt_epochs"],
        learning_rate=cfg["training"]["target_adapt_lr"],
        weight_decay=cfg["training"]["weight_decay"],
        center_loss_weight=cfg["training"]["center_loss_weight"],
        gradient_clip_norm=cfg["training"].get("gradient_clip_norm"),
        stage_name="target-adapt",
    )

    center_cfg = get_center_config(cfg)

    target_center = compute_center(
        model,
        target_val_loader,
        device,
        desc="Computing target normal center/prototypes",
        num_prototypes=center_cfg["num_prototypes"],
        prototype_method=center_cfg["prototype_method"],
        seed=center_cfg["seed"],
    )

    print("[Saving trained model]")
    torch.save(model.state_dict(), out_dir / "model.pt")

    print("[Saving target normal center/prototypes]")
    torch.save(target_center.cpu(), out_dir / "target_normal_center.pt")

    print("[Saving tokenizer]")
    tokenizer.save_pretrained(out_dir / "tokenizer")

    save_json(
        {
            "stage": "train",
            "mode": "fewshot_target_adaptation",
            "source_history": source_history,
            "target_history": target_history,
            "source_datasets": source_datasets,
            "target_dataset": target_dataset,
            "target_adapt_size": int(len(target_adapt_df)),
            "normal_center": center_cfg,
            "saved_model": str(out_dir / "model.pt"),
            "saved_center": str(out_dir / "target_normal_center.pt"),
            "saved_tokenizer": str(out_dir / "tokenizer"),
        },
        out_dir / "train_results.json",
    )

    print("=" * 80)
    print("[FEW-SHOT TARGET ADAPTATION TRAINING FINISHED]")
    print(f"Saved model     : {out_dir / 'model.pt'}")
    print(f"Saved center    : {out_dir / 'target_normal_center.pt'}")
    print(f"Saved tokenizer : {out_dir / 'tokenizer'}")
    print("=" * 80)


# ======================================================
# MODE 2: FEW-SHOT TARGET ADAPTATION PREDICT ONLY
# ======================================================


def predict_fewshot_target_adaptation(cfg):
    """
    Cross-domain/few-shot target prediction with the SAME validation-only
    tuning protocol used in-domain.

    All tuning uses TARGET NORMAL validation samples and synthetic corruptions
    derived from those samples. Real target anomaly validation labels and target
    test data are not used for tuning.
    """
    out_dir = ensure_output_dir(cfg)

    seed = int(cfg["experiment"].get("seed", 42))
    set_seed(seed)
    device = get_device(cfg["training"].get("device", "auto"))

    mode_cfg = cfg["datasets"]["fewshot_target_adaptation"]
    target_dataset = mode_cfg["target_dataset"]

    print("=" * 80)
    print("[Stage] PREDICT ONLY")
    print("[Mode] fewshot_target_adaptation")
    print(f"[Target dataset] {target_dataset}")
    print(f"[Scoring version] {ROBUST_SCORING_VERSION}")
    print("=" * 80)

    # STEP 1 - load target-adapted model
    print("[STEP 1/10] Load target-adapted model, tokenizer, and target center")
    model, tokenizer, target_center = load_saved_model_tokenizer_center(
        cfg=cfg,
        out_dir=out_dir,
        device=device,
        center_filename="target_normal_center.pt",
    )

    # STEP 2 - target normal validation only
    print("[STEP 2/10] Load TARGET NORMAL validation samples only")
    target_val_normal_df = load_sequences_for_dataset(
        cfg,
        dataset=target_dataset,
        split=mode_cfg["target_val_split"],
        normal_only=True,
    )
    print(f"[Target normal validation sequences] {len(target_val_normal_df)}")

    # STEPS 3-7 - target validation-only tuning
    print("[STEP 3-7/10] TARGET validation-only robust tuning with synthetic anomalies")
    robust_params, robust_threshold, robust_val_normal_scores, tuning_df = (
        fit_and_tune_robust_scoring(
            cfg=cfg,
            val_normal_df=target_val_normal_df,
            model=model,
            tokenizer=tokenizer,
            center=target_center,
            device=device,
            seed=seed,
            desc_prefix=f"{target_dataset} target validation tuning",
        )
    )
    robust_params["target_dataset"] = target_dataset

    save_json(robust_params, out_dir / "robust_scoring_params.json")
    tuning_df.to_csv(out_dir / "robust_tuning_search.csv", index=False)
    robust_val_normal_scores.to_csv(
        out_dir / "robust_normal_validation_scores.csv", index=False
    )

    print("[TARGET TEST HAS NOT BEEN LOADED YET]")

    # STEP 8 - only now load target test
    print("[STEP 8/10] Load held-out TARGET TEST after tuning is frozen")
    target_test_df = load_sequences_for_dataset(
        cfg,
        dataset=target_dataset,
        split=mode_cfg["target_test_split"],
        normal_only=mode_cfg.get("target_test_normal_only", False),
    )
    print(f"[Target test sequences] {len(target_test_df)}")

    target_test_loader = make_loader(
        cfg, target_test_df, tokenizer, shuffle=False
    )

    # STEP 9 - apply frozen scoring
    print("[STEP 9/10] Score TARGET TEST and apply FROZEN robust parameters")
    test_raw_scores = score_loader(
        model,
        target_test_loader,
        target_center,
        device,
        alpha_mlm=COMPONENT_EXTRACTION_MLM_WEIGHT,
        beta_center=COMPONENT_EXTRACTION_CENTER_WEIGHT,
        desc="Scoring held-out TARGET TEST components",
    )
    robust_test_scores = apply_robust_score_normalization(
        test_raw_scores, robust_params
    )
    robust_test_scores["prediction"] = (
        robust_test_scores["score"] > robust_threshold
    ).astype(int)

    # STEP 10 - final evaluation only
    print("[STEP 10/10] Use TARGET TEST labels only for final metrics")
    metrics = evaluate_scores(
        robust_test_scores,
        robust_threshold,
        normal_label=0,
    )

    save_classification_report_files(metrics, out_dir, prefix="test")
    robust_test_scores.to_csv(
        out_dir / cfg["outputs"].get("predictions_file", "predictions.csv"),
        index=False,
    )

    save_json(
        {
            "stage": "predict",
            "mode": "fewshot_target_adaptation",
            "target_dataset": target_dataset,
            "metrics": metrics,
            "robust_scoring": robust_params,
            "robust_threshold": float(robust_threshold),
        },
        out_dir / cfg["outputs"].get("results_file", "results.json"),
    )

    print("=" * 80)
    print("[FEW-SHOT TARGET ADAPTATION PREDICTION FINISHED]")
    print("[Weight-Tuned Robust FINAL TARGET TEST Classification Report]")
    print(metrics["classification_report_text"])
    print("=" * 80)

def run_fewshot_target_adaptation(cfg, config_path: str):
    """
    Full few-shot target adaptation pipeline:
        train
        predict
    """

    train_fewshot_target_adaptation(cfg, config_path)
    predict_fewshot_target_adaptation(cfg)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True, help="Path to YAML config.")
    args = parser.parse_args()

    cfg = load_config(args.config)
    print(f"[RUN.PY PATH] {Path(__file__).resolve()}")
    print(f"[Scoring implementation] {ROBUST_SCORING_VERSION}")
    mode = cfg["experiment"]["mode"]
    stage = cfg["experiment"].get("stage", "train_predict")

    if mode == "in_domain":
        if stage == "train":
            train_in_domain(cfg, args.config)
        elif stage == "predict":
            predict_in_domain(cfg)
        elif stage == "train_predict":
            run_in_domain(cfg, args.config)
        else:
            raise ValueError(
                f"Unsupported stage for in_domain: {stage}. "
                "Use 'train', 'predict', or 'train_predict'."
            )

    elif mode == "fewshot_target_adaptation":
        if stage == "train":
            train_fewshot_target_adaptation(cfg, args.config)
        elif stage == "predict":
            predict_fewshot_target_adaptation(cfg)
        elif stage == "train_predict":
            run_fewshot_target_adaptation(cfg, args.config)
        else:
            raise ValueError(
                f"Unsupported stage for fewshot_target_adaptation: {stage}. "
                "Use 'train', 'predict', or 'train_predict'."
            )
    else:
        raise ValueError(
            f"Unsupported mode: {mode}. "
            "Use 'in_domain' or 'fewshot_target_adaptation'."
        )


if __name__ == "__main__":
    main()